FROM node:14.17
WORKDIR /usr
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY setup ./setup
COPY @types ./@types
RUN ls -a
RUN yarn install
EXPOSE 8000
CMD ["car", "package.json"]
CMD ["yarn","start"]